# This file is part of the NuCms package.
# (c) Jacek Bednarek

nucms_admin_locale:
    type: sylius.resource
    resource: |
        alias: nucms.file
        section: admin
        templates: '@NugatoNuCms/Admin/Crud'
        grid: nucms_admin_file
        redirect: update
