# This file is part of the NuCms package.
# (c) Jacek Bednarek

nucms_admin_settings:
    type: sylius.resource
    resource: |
        alias: nucms.settings
        section: admin
        templates: '@NugatoNuCms/Admin/Crud'
        grid: nucms_admin_settings
        redirect: update
        vars:
            all:
                header: nucms.ui.settings
