# This file is part of the NuCms package.
# (c) Jacek Bednarek

nucms_admin_ajax_taxon_by_name_phrase:
    path: /search
    methods: [GET]
    defaults:
        _controller: sylius.controller.taxon:indexAction
        _sylius:
            serialization_groups: [Autocomplete]
            permission: true
            repository:
                method: findByNamePart
                arguments:
                    phrase: $phrase
