# This file is part of the NuCms package.
# (c) Jacek Bednarek

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Nugato\Bundle\NuCmsBundle\Controller\Web\:
        resource: '../../../Controller/Web'
        tags: ['controller.service_arguments']
