# This file is part of the NuCms package.
# (c) Jacek Bednarek

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Nugato\Bundle\NuCmsBundle\Controller\Web\PageController:
#        class: Nugato\Bundle\NuCmsBundle\Controller\Web\PageController
        arguments:
            - '@nucms.context.locale.request_based_with_default'
            - '@sylius.locale_provider'
            - '@nucms.repository.page'
        tags: ['controller.service_arguments']

    nucms.controller.web.locale_switch:
        class: Nugato\Bundle\NuCmsBundle\Controller\Web\LocaleSwitchController
        arguments:
            - '@nucms.context.locale.request_based_with_default'
            - '@sylius.locale_provider'
        tags: ['controller.service_arguments']

    nucms.controller.web.navigation:
        class: Nugato\Bundle\NuCmsBundle\Controller\Web\NavigationController
        arguments:
            - '@nucms.context.locale.request_based_with_default'
            - '@nucms.repository.navigation'
            - '@nucms.repository.navigation_item'
        tags: ['controller.service_arguments']
