# This file is part of the NuCms package.
# (c) Jacek Bednarek

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Form
    Nugato\Bundle\NuCmsBundle\Component\Settings\Form\DataTransformer\SettingsTypeDataTransformer:
    Nugato\Bundle\NuCmsBundle\Component\Settings\Form\DataTransformer\SettingsCheckboxContentDataTransformer:

    Nugato\Bundle\NuCmsBundle\Component\Settings\Form\SettingsType:
        arguments: ['%nucms.model.settings.class%', ['sylius']]

    Nugato\Bundle\NuCmsBundle\Component\Settings\Form\SettingsInputTranslationType:
        arguments: ['%nucms.model.settings_translation.class%', ['sylius']]

    Nugato\Bundle\NuCmsBundle\Component\Settings\Form\SettingsCheckboxTranslationType:
        arguments: ['%nucms.model.settings_translation.class%', ['sylius']]

    # Fixtures
    Nugato\Bundle\NuCmsBundle\Component\Settings\Fixture\SettingsFixture:
        arguments: ['@nucms.factory.settings', '@nucms.factory.settings_translation', '@nucms.manager.settings']
        tags: [sylius_fixtures.fixture]
