services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Form
    Nugato\Bundle\NuCmsBundle\Form\TaxonType:
        arguments: ['%nucms.model.taxon.class%', ['sylius']]
        tags: [{ name: form.type }]

    # Fixtures
    nucms.fixture.taxon:
        class: Nugato\Bundle\NuCmsBundle\Component\Taxon\Fixture\TaxonFixture
        arguments:
            - '@nucms.factory.taxon'
            - '@nucms.factory.taxon_translation'
            - '@nucms.manager.taxon'
        tags: [sylius_fixtures.fixture]
