# This file is part of the NuCms package.
# (c) Jacek Bednarek

Nugato\Bundle\NuCmsBundle\Component\Navigation\Entity\NavigationItemTranslation:
    type: entity
    table: nucms_navigation_item_translation
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        url:
            type: string
            length: 255
    indexes:
        search_idx:
            columns: name
    lifecycleCallbacks: {  }
