# This file is part of the NuCms package.
# (c) Jacek Bednarek

Nugato\Bundle\NuCmsBundle\Component\Taxon\Entity\TaxonTranslation:
    type: entity
    table: nucms_taxon_translation
    lifecycleCallbacks: {  }
