# This file is part of the NuCms package.
# (c) Jacek Bednarek

Nugato\Bundle\NuCmsBundle\Entity\Taxon:
    type: entity
    table: nucms_taxon
    repositoryClass: Sylius\Bundle\TaxonomyBundle\Doctrine\ORM\TaxonRepository
    lifecycleCallbacks: {  }
    manyToOne:
        image:
            targetEntity: Nugato\Bundle\NuCmsBundle\Entity\File\File
            joinColumn:
                name: image
                referencedColumnName: id
                nullable: true
                onDelete: CASCADE
