# This file is part of the NuCms package.
# (c) Jacek Bednarek

parameters:
    admin_prefix: 'admin'
    nucms.file.uploader.filesystem: nucms_file
    mailer_user_name: nucms
    mailer_user: dev@nugato.pl

imports:
    - { resource: "@NugatoNuCmsBundle/Resources/config/services.yml" }
    - { resource: "@NugatoNuCmsBundle/Resources/config/resources.yml" }
    - { resource: "@NugatoNuCmsBundle/Resources/config/grids.yml" }
    - { resource: "@NugatoNuCmsBundle/Resources/config/users.yml" }
    - { resource: "@NugatoNuCmsBundle/Resources/config/fixtures.yml" }
    - { resource: "@SyliusTaxonomyBundle/Resources/config/app/config.yml" }

framework:
    templating:
        engines: ['twig']

doctrine:
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            NugatoNuCmsBundle:
                is_bundle: true
                type: yml
                dir: 'Resources/config/doctrine'
                prefix: 'Nugato\Bundle\NuCmsBundle'

stof_doctrine_extensions:
    orm:
        default:
            timestampable: true
            sluggable: true
            tree: true

knp_gaufrette:
    adapters:
        nucms_file:
            local:
                directory: "%kernel.project_dir%/public/upload"
                create: true
    filesystems:
        nucms_file:
            adapter: '%nucms.file.uploader.filesystem%'
            alias: nucms_filesystem

liip_imagine:
    filter_sets:
        xs:
            filters:
                thumbnail: { size: [40, 40], mode: inset }
        sm:
            filters:
                thumbnail: { size: [120, 90], mode: inset }
        md:
            filters:
                thumbnail: { size: [240, 180], mode: inset }
        lg:
            filters:
                thumbnail: { size: [640, 480], mode: inset }

sylius_mailer:
    sender:
        name: '%mailer_user_name%'
        address: '%mailer_user%'
    emails:
        contact_form:
            subject: Contact form
            template: '@NugatoNuCms/Web/Email/email_contact_form.html.twig'

nugato_nu_cms:
    page:
        templates:
            - { code: 'default', label: 'nucms.ui.page_templates.default', template: '@NugatoNuCms/Web/Page/Template/default.html.twig' }
            - { code: 'contact', label: 'nucms.ui.page_templates.contact', template: '@NugatoNuCms/Web/Page/Template/contact.html.twig' }
