# This file is part of the NuCms package.
# (c) Jacek Bednarek

parameters:
    admin_prefix: 'admin'
    nucms.file.uploader.filesystem: nucms_file

imports:
    - { resource: "@NugatoNuCmsBundle/Resources/config/services.yml" }
    - { resource: "@NugatoNuCmsBundle/Resources/config/resources.yml" }
    - { resource: "@NugatoNuCmsBundle/Resources/config/grids.yml" }
    - { resource: "@NugatoNuCmsBundle/Resources/config/users.yml" }
    - { resource: "@NugatoNuCmsBundle/Resources/config/fixtures.yml" }
    - { resource: "@SyliusTaxonomyBundle/Resources/config/app/config.yml" }

framework:
    templating:
        engines: ['twig']

fos_rest:
    exception: ~
    view:
        formats:
            json: true
        empty_content: 204
    format_listener:
        rules:
            - { path: '^/api', priorities: ['json'], fallback_format: json, prefer_extension: true }
            - { path: '^/', stop: true }

doctrine_migrations:
    dir_name: "%kernel.root_dir%/migrations"
    namespace: Nugato\NuCmsBundle\Migrations
    table_name: migration_versions
    name: Nugato NuCms Migrations
    organize_migrations: false
    custom_template: ~

doctrine:
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            NugatoNuCmsBundle:
                is_bundle: true
                type: yml
                dir: 'Resources/config/doctrine'
                prefix: 'Nugato\Bundle\NuCmsBundle'

stof_doctrine_extensions:
    orm:
        default:
            timestampable: true
            sluggable: true
            tree: true

knp_gaufrette:
    adapters:
        nucms_file:
            local:
                directory: "%kernel.root_dir%/../web/upload"
                create: true
    filesystems:
        nucms_file:
            adapter: '%nucms.file.uploader.filesystem%'
            alias: nucms_filesystem

liip_imagine:
    loaders:
        default:
            filesystem:
                data_root: "%kernel.root_dir%/../web/upload"
    filter_sets:
        xs:
            filters:
                thumbnail: { size: [40, 40], mode: inset }
        sm:
            filters:
                thumbnail: { size: [120, 90], mode: inset }
        md:
            filters:
                thumbnail: { size: [240, 180], mode: inset }
        lg:
            filters:
                thumbnail: { size: [640, 480], mode: inset }

nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: []
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
        hosts: []
        origin_regex: false
        forced_allow_origin_value: ~
    paths:
        '^/':
            allow_origin: ['*']
            allow_headers: ["*"]
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
            max_age: 3600

sylius_mailer:
    sender:
        name: '%mailer_user_name%'
        address: '%mailer_user%'
    emails:
        contact_form:
            subject: Contact form
            template: '@NugatoNuCms/Web/Email/email_contact_form.html.twig'

nugato_nu_cms:
    page:
        templates:
            - { code: 'default', label: 'nucms.ui.page.template.default', template: '@NugatoNuCms/Web/Page/Template/default.html.twig' }
            - { code: 'contact', label: 'nucms.ui.page.template.contact', template: '@NugatoNuCms/Web/Page/Template/contact.html.twig' }
