# This file is part of the NuCms package.
# (c) Jacek Bednarek

imports:
    - { resource: 'grids/admin/*.yaml' }
    - { resource: 'grids/api/*.yaml' }

sylius_grid:
    templates:
        action:
            create: '@NugatoNuCms/Admin/Crud/Action/create.html.twig'
            update: '@NugatoNuCms/Admin/Crud/Action/update.html.twig'
            delete: '@NugatoNuCms/Admin/Crud/Action/delete.html.twig'
