# This file is part of the NuCms package.
# (c) Jacek Bednarek

imports:
    - { resource: 'resources/*.yml' }

sylius_resource:
    translation:
        locale_provider: 'nucms.translation_locale_provider'
