# This file is part of the NuCms package.
# (c) Jacek Bednarek

nucms_admin:
    prefix: /admin
    resource: routing/admin.yaml
    trailing_slash_on_root: false

nucms_web:
    prefix: /
    resource: routing/web.yaml

nucms_api:
    prefix: /api/v1
    resource: routing/api.yaml
