# This file is part of the NuCms package.
# (c) Jacek Bednarek

sylius_user:
    driver: doctrine/orm
    resources:
        admin:
            user:
                classes:
                    model: Nugato\Bundle\NuCmsBundle\Component\User\Entity\User
                    repository: Sylius\Bundle\UserBundle\Doctrine\ORM\UserRepository
                    # @todo with _remember_me form
                    interface: Sylius\Component\User\Model\UserInterface
#        oauth:
#            user:
#                classes:
#                    model: Nugato\Bundle\NuCmsBundle\Component\User\Entity\UserOAuth
#                    interface: Sylius\Component\User\Model\UserOAuthInterface
