# This file is part of the NuCms package.
# (c) Jacek Bednarek

nucms_admin_partial:
    resource: admin/partial.yaml
    prefix: /_partial

nucms_admin_ajax:
    resource: admin/ajax.yaml
    prefix: /ajax
    defaults:
        _format: json

nucms_admin_dashboard:
    path: /
    methods: [GET]
    defaults:
        _controller: NugatoNuCmsBundle:Admin\Dashboard:index

nucms_admin_security:
    resource: admin/security.yaml

nucms_admin_locale:
    resource: admin/locale.yaml

nucms_admin_page:
    resource: admin/page.yaml

nucms_admin_taxon:
    resource: admin/taxon.yaml

nucms_admin_navigation:
    resource: admin/navigation.yaml

nucms_admin_file:
    resource: admin/file.yaml

nucms_admin_settings:
    resource: admin/settings.yaml

nucms_admin_blog:
    resource: admin/blog.yaml
