# This file is part of the NuCms package.
# (c) Jacek Bednarek

nucms_api_page:
    type: sylius.resource_api
    resource: |
        alias: nucms.page
        section: api
        serialization_version: 1

nucms_api_locale:
    type: sylius.resource_api
    resource: |
        alias: nucms.locale
        section: api
        serialization_version: 1

nucms_api_file_bulk_delete:
    path: /files/bulk-delete
    methods: [DELETE]
    defaults:
        _controller: nucms.controller.file:bulkDeleteApiAction
        _sylius:
            section: api
            serialization_version: 1
            csrf_protection: false

nucms_api_file:
    type: sylius.resource_api
    resource: |
        alias: nucms.file
        section: api
        serialization_version: 1
        grid: nucms_api_file
