# This file is part of the NuCms package.
# (c) Jacek Bednarek

nucms_web_homepage:
    path: /
    defaults: { _controller: 'Nugato\Bundle\NuCmsBundle\Controller\Web\PageController:homePage' }

nucms_web_blog:
    resource: web/blog.yaml
    prefix: /blog
    trailing_slash_on_root: false

nucms_web_homepage_locale:
    path: /{_locale}/
    defaults: { _controller: 'Nugato\Bundle\NuCmsBundle\Controller\Web\PageController:homePage', _locale: '%locale%' }
    requirements:
        _locale: ^[a-z]{2}(?:_[A-Z]{2})?$

nucms_web_single_page:
    path: /{slug}
    defaults: { _controller: 'Nugato\Bundle\NuCmsBundle\Controller\Web\PageController:singlePage', _locale: '%locale%' }
    requirements:
        _locale: ^[a-z]{2}(?:_[A-Z]{2})?$

nucms_web_single_page_locale:
    path: /{_locale}/{slug}
    defaults: { _controller: 'Nugato\Bundle\NuCmsBundle\Controller\Web\PageController:singlePage', _locale: '%locale%' }
    requirements:
        _locale: ^[a-z]{2}(?:_[A-Z]{2})?$

nucms_web_locale_switch:
    path: /locale-switch/{code}
    methods: [GET]
    defaults: { _controller: 'Nugato\Bundle\NuCmsBundle\Controller\Web\LocaleSwitchController:switch' }

nucms_web_contact_send:
    path: /contact-form/send
    methods: [POST]
    defaults: { _controller: 'Nugato\Bundle\NuCmsBundle\Controller\Web\ContactController:sendForm' }
