# This file is part of the NuCms package.
# (c) Jacek Bednarek

sylius_grid:
    grids:
        nucms_admin_file:
            driver:
                name: doctrine/orm
                options:
                    class: '%nucms.model.file.class%'
            sorting:
                id: desc
            fields:
                file:
                    type: twig
                    label: nucms.ui.file
                    path: .
                    options:
                        template: "@NugatoNuCms/Admin/Crud/Field/file.html.twig"
                id:
                    type: string
                    sortable: true
                title:
                    type: string
                    label: nucms.ui.name
                    sortable: true
            filters:
                title:
                    type: string
            actions:
                main:
                    create:
                        type: create
                        label: nucms.ui.create
                        enabled: true
                        position: 100
                item:
                    update:
                        type: update
                        label: nucms.ui.edit
                        enabled: true
                        position: 100
                        options: { }
                    delete:
                        type: delete
                        enabled: true
                        position: 101
                        options: { }
                bulk:
                    delete:
                        type: delete
                        label: nucms.ui.delete
                        enabled: true
                        position: 100
                        options: { }