# This file is part of the NuCms package.
# (c) Jacek Bednarek

sylius_resource:
    resources:
        nucms.file:
            driver: doctrine/orm
            classes:
                model: Nugato\Bundle\NuCmsBundle\Entity\File\File
                form: Nugato\Bundle\NuCmsBundle\Form\File\FileType
                repository: Nugato\Bundle\NuCmsBundle\Repository\File\FileRepository
                controller: Nugato\Bundle\NuCmsBundle\Controller\Admin\FileController
