# This file is part of the NuCms package.
# (c) Jacek Bednarek

sylius_resource:
    resources:
        nucms.navigation:
            driver: doctrine/orm
            classes:
                model: Nugato\Bundle\NuCmsBundle\Component\Navigation\Entity\Navigation
                form: Nugato\Bundle\NuCmsBundle\Component\Navigation\Form\NavigationType
                repository: Nugato\Bundle\NuCmsBundle\Component\Navigation\Repository\NavigationRepository

        nucms.navigation_item:
            driver: doctrine/orm
            classes:
                model: Nugato\Bundle\NuCmsBundle\Component\Navigation\Entity\NavigationItem
                form: Nugato\Bundle\NuCmsBundle\Component\Navigation\Form\NavigationItemType
                repository: Nugato\Bundle\NuCmsBundle\Component\Navigation\Repository\NavigationItemRepository
            translation:
                classes:
                    model: Nugato\Bundle\NuCmsBundle\Component\Navigation\Entity\NavigationItemTranslation
                    form: Nugato\Bundle\NuCmsBundle\Component\Navigation\Form\NavigationItemTranslationType
