# This file is part of the NuCms package.
# (c) Jacek Bednarek

sylius_resource:
    resources:
        nucms.taxon:
            driver: doctrine/orm
            classes:
                model: Nugato\Bundle\NuCmsBundle\Component\Taxon\Entity\Taxon
                form: Nugato\Bundle\NuCmsBundle\Form\TaxonType
                repository: Nugato\Bundle\NuCmsBundle\Component\Taxon\Repository\TaxonRepository
            translation:
                classes:
                    model: Nugato\Bundle\NuCmsBundle\Component\Taxon\Entity\TaxonTranslation
                    form: Sylius\Bundle\TaxonomyBundle\Form\Type\TaxonTranslationType

sylius_taxonomy:
    driver: doctrine/orm
    resources:
        taxon:
            classes:
                model: Nugato\Bundle\NuCmsBundle\Component\Taxon\Entity\Taxon
                repository: Nugato\Bundle\NuCmsBundle\Component\Taxon\Repository\TaxonRepository
            translation:
                classes:
                    model: Nugato\Bundle\NuCmsBundle\Component\Taxon\Entity\TaxonTranslation
